# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: 

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://jillsuecamp.github.io/HenHacks"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Example Hacks | 5-6 August 2022"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "HenHacks"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  date:        "5 - 6 August 2022"
  location:    "Holmdel, NJ, United States"
  dateTime:
    year: "2024"
    month: "March"
    day:  "2"
    hour: "10"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  display_schedule: "true"

  hero:
    links:
      - text: "Register!"
        href: "https://docs.google.com/forms/d/1Spd7-BngzG0EgO1-h5Vms70XPXS2xKmqdfWAOUNahjM"
      - text: "Sponsor Us!"
        href: "mailto:sponsorship@website.com"

  about:
    description: >
     Join us as HenHacks makes its proud return for a second year, bringing together over [theme] students from across the state. This beginner-friendly hackathon takes place right on the University of Delaware campus and is open to college students of all majors. Our mission is to empower students by enhancing their technical skills, equipping them to positively impact their communities and excel in technology-related careers.


  # Info Sections
  info:
    description: >
        Theme~ Hack to save the world! 
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
